# Generated by Django 4.0.7 on 2023-08-27 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audioupload', '0002_alter_uploadedaudio_audio_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedaudio',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
