# Generated by Django 4.0.7 on 2023-08-27 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('audioupload', '0003_alter_uploadedaudio_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedaudio',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='uploadedaudio',
            name='audio_file',
            field=models.FileField(upload_to='uploaded_audio/'),
        ),
        migrations.AlterField(
            model_name='uploadedaudio',
            name='size',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='uploadedaudio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
